### ISSUE TITLE
problem with importing ebucoreplus.owl in protégé

### ISSUE THREAD

**Issue by RendersKoen** [ebu/ebucoreplus#341]
Hi all, new here to the forum (I did register some time ago, but didn't get to posting yet)

I downloaded the ebucoreplus.owl from the code page here, but when I want to open it in protégé i get a load of errors and  it wont load at all..

I tried in 5.0 and 5.6 (newest version)

Any idea what might be wrong?

This is the full stack trace:

org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=13:column=4] Expecting rdf:RDF element.

Full Stack Trace
-----------------------------------------------------------------------------------------

org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFXMLParserException: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=13:column=4] Expecting rdf:RDF element.
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:74)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1303)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1243)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1200)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInternal(OntologyLoader.java:116)
	at org.protege.editor.owl.model.io.OntologyLoader.lambda$loadOntologyInOtherThread$0(OntologyLoader.java:71)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=13:column=4] Expecting rdf:RDF element.
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.verify(RDFParser.java:447)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.StartRDF.startElement(StartRDF.java:187)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:208)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:151)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:71)
	... 10 more

**Comment by JuergenGrupp** [comment]
Welcome @RendersKoen to EBUCorePlus!

I am not really sure what the problem is. But I would recommend to use the GitHub Desktop application to synchronize your local repo. From there you can open the local repo in your Explorer tool and then right click (or other context menu access) to open the ebucoreplus.owl file with Protégé. 

At least that worked for me, even if I cannot explain why. And I sometimes also have parsing problems, usually when GitHub Desktop is NOT up and running. So, I restart GitHub, synchronize again and open the file with Protégé again. I hope this helps.

**Comment by RendersKoen** [comment]
Thanks @JuergenGrupp for the quick reply. That worked, thanks!!
